import wave
import struct
import argparse
import sys
import numpy as np
from scipy.signal import firwin

def write_verilog_headers(config_file, fir_file, max_addr, downsample_factor, num_taps=31):
    """Generates pure Verilog header files containing constants and coefficients."""
    # 1. Write the global configuration macros
    try:
        with open(config_file, 'w') as f:
            f.write(f"// Auto-generated by wav2mem.py. Do not edit.\n")
            f.write(f"`define CONFIG_MAX_ADDR {max_addr}\n")
            f.write(f"`define CONFIG_DOWNSAMPLE {downsample_factor}\n")
        print(f"Generated {config_file}")
    except IOError as e:
        sys.exit(f"Error writing config header: {e}")

    # 2. Compute FIR lowpass filter coefficients
    fs_dac = 48000
    effective_fs = fs_dac / downsample_factor
    cutoff_hz = (effective_fs / 2) * 0.9  # 90% of Nyquist to prevent aliasing
    nyquist_dac = fs_dac / 2
    normalized_cutoff = cutoff_hz / nyquist_dac
    
    coeffs = firwin(num_taps, normalized_cutoff, window='hamming')
    q15_coeffs = np.round(coeffs * 32768).astype(int)
    print (f"Generated FIR coefficients for cutoff {cutoff_hz/1000}KHz")
    # 3. Write the case-statement lines to the FIR header
    try:
        with open(fir_file, 'w') as f:
            f.write(f"// Auto-generated FIR Coefficients for {downsample_factor}x downsampling\n")
            for i, coef in enumerate(q15_coeffs):
                if coef < 0:
                    f.write(f"5'd{i}: coefficient = -16'sd{abs(coef)};\n")
                else:
                    f.write(f"5'd{i}: coefficient = 16'sd{coef};\n")
        print(f"Generated {fir_file}")
    except IOError as e:
        sys.exit(f"Error writing FIR header: {e}")

def wav_to_mem(input_wav, output_mem, downsample_factor, config_file, fir_file, max_samples):
    try:
        with wave.open(input_wav, 'rb') as wav_file:
            channels = wav_file.getnchannels()
            sample_width = wav_file.getsampwidth()
            num_frames = wav_file.getnframes()
            
            if sample_width != 2:
                sys.exit("Error: Audio must be 16-bit.")
            
            # Calculate the maximum number of raw frames we can accept
            max_raw_frames_allowed = max_samples * downsample_factor
            
            # Determine how many raw frames we will actually read
            if num_frames > max_raw_frames_allowed:
                print(f"Warning: Audio file is too large for the Basys 3 BRAM layout.\n"
                      f"         Truncating to the first {max_samples} downsampled samples.")
                frames_to_read = max_raw_frames_allowed
            else:
                frames_to_read = num_frames
            
            # Read the precise amount of raw data needed
            raw_data = wav_file.readframes(frames_to_read)
            bytes_per_frame = channels * sample_width
            
            sample_count = 0
            with open(output_mem, 'w') as mem_file:
                # Loop through the raw frames using the downsample factor as the step
                for i in range(0, frames_to_read, downsample_factor):
                    frame_start = i * bytes_per_frame
                    sample = struct.unpack_from('<h', raw_data, frame_start)[0]
                    hex_sample = format(sample & 0xFFFF, '04X')
                    mem_file.write(hex_sample + '\n')
                    sample_count += 1
                    
            print(f"Success! Processed {sample_count} samples at {downsample_factor}x downsampling.")
            
            # Generate the header files for Verilog
            write_verilog_headers(config_file, fir_file, sample_count - 1, downsample_factor)
            
    except Exception as e:
        sys.exit(f"Error processing WAV: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert WAV to MEM and generate Verilog configuration headers.")
    parser.add_argument("input_wav", help="Input .wav file")
    parser.add_argument("output_mem", help="Output .mem file")
    parser.add_argument("-d", "--downsample", type=int, default=16, help="Downsampling factor.")
    parser.add_argument("--hc", default="audio_config.vh", help="Output config header filename")
    parser.add_argument("--hf", default="fir_coefficients.vh", help="Output FIR coefficients header filename")
    parser.add_argument("--max_samples", type=int, default=5_000_000, help="Maximum number of samples to process after downsampling.")
    
    args = parser.parse_args()
    wav_to_mem(args.input_wav, args.output_mem, args.downsample, args.hc, args.hf,args.max_samples)